# Site settings
title: AK
tagline: Dev
email: aokincaid@gmail.com
description: Austin Kincaid's personal portfolio.
url: "http://aceokay.github.io" # the base hostname & protocol for your site
github_username: aceokay

# Build settings
markdown: kramdown
